# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Claus

# nothing here

CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_IPV6=y
CONFIG_NET_TCP=y
CONFIG_NET_UDP=y
CONFIG_NET_MGMT=y
CONFIG_NET_CONFIG_AUTO_INIT=n
CONFIG_ETH_DRIVER=n
CONFIG_TEST_RANDOM_GENERATOR=y
CONFIG_NET_L2_ETHERNET=y
CONFIG_NET_SHELL=y
# dhcp
CONFIG_NET_DHCPV4=y
CONFIG_NET_DHCPV4_SERVER=y
CONFIG_WIFI_QCOM_AUTO_DHCPV4=y

CONFIG_WIFI=y
CONFIG_WIFI_QCOM=y
CONFIG_NET_L2_WIFI_SHELL=y
CONFIG_NET_MGMT_EVENT_QUEUE_TIMEOUT=5000
CONFIG_NET_MGMT_EVENT_QUEUE_SIZE=16
CONFIG_NET_L2_WIFI_MGMT=y

CONFIG_NET_LOG=y
CONFIG_NET_L2_ETHERNET_LOG_LEVEL_DBG=n
CONFIG_NET_L2_WIFI_MGMT_LOG_LEVEL_DBG=y
CONFIG_NET_MGMT_EVENT_LOG_LEVEL_DBG=n
CONFIG_WIFI_LOG_LEVEL_DBG=y

# increase CONFIG_NET_BUF_DATA_SIZE to 512, allow more net buffer allocated.
CONFIG_NET_BUF_DATA_SIZE=512
# increase NET_MGMT_EVENT_STACK_SIZE to 1024, fix potential stack overflow issues.
CONFIG_NET_MGMT_EVENT_STACK_SIZE=1024
# increase SYSTEM_WORKQUEUE_STACK_SIZE to 2048, fix potential stack overflow issues.
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

# zperf
CONFIG_NET_ZPERF=y
CONFIG_NET_ZPERF_SERVER=y
# allow more ZVFS_POLL
CONFIG_ZVFS_POLL_MAX=16

#power
CONFIG_PM=y
CONFIG_STATS=y
CONFIG_PM_STATS=y

# counter driver.
CONFIG_COUNTER=y

# avoid stack overflow in the idle task thread.
CONFIG_IDLE_STACK_SIZE=512

# enable SEGGER RTT
#CONFIG_UART_CONSOLE=n
#CONFIG_RTT_CONSOLE=y
#CONFIG_USE_SEGGER_RTT=y
#CONFIG_SHELL_BACKEND_SERIAL=n
#CONFIG_SHELL_BACKEND_RTT=y

# Crash dump configuration of two backend options:
# 1) Logging backend:
#    # CONFIG_DEBUG_COREDUMP=y
#    # CONFIG_DEBUG_COREDUMP_BACKEND_LOGGING=y
# 2) Flash partition backend:
#    # CONFIG_DEBUG_COREDUMP=y
#    # CONFIG_DEBUG_COREDUMP_BACKEND_FLASH_PARTITION=y
#    # CONFIG_DEBUG_COREDUMP_SHELL=y
#    # CONFIG_FLASH=y
#    # CONFIG_FLASH_MAP=y
#    # CONFIG_FLASH_PAGE_LAYOUT=y

CONFIG_FLASH=y
CONFIG_FLASH_QCC730=y
CONFIG_BOARD_QCC730_UART_GPIO_OPTION=1
CONFIG_PM_DEVICE=y

CONFIG_QCRYPTO=y