# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause

# nothing here
CONFIG_PM=y
CONFIG_STATS=y
CONFIG_PM_STATS=y
CONFIG_PM_S2RAM=y

# counter driver.
CONFIG_COUNTER=y
# avoid stack overflow in the idle task thread.
CONFIG_IDLE_STACK_SIZE=512
