# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause

# nothing here
CONFIG_PM=y
CONFIG_STATS=y
CONFIG_PM_STATS=y
CONFIG_PM_S2RAM=y

# counter driver.
CONFIG_COUNTER=y
# avoid stack overflow in the idle task thread.
CONFIG_IDLE_STACK_SIZE=512

#wifi
CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_IPV6=y
CONFIG_NET_TCP=y
CONFIG_NET_UDP=y
CONFIG_NET_MGMT=y
CONFIG_NET_CONFIG_AUTO_INIT=n
CONFIG_ETH_DRIVER=n
CONFIG_TEST_RANDOM_GENERATOR=y
CONFIG_NET_L2_ETHERNET=y
CONFIG_NET_SHELL=y
# dhcp
CONFIG_NET_DHCPV4=y
CONFIG_NET_DHCPV4_SERVER=y
CONFIG_WIFI_QCOM_AUTO_DHCPV4=y

CONFIG_WIFI=y
CONFIG_WIFI_QCOM=y
CONFIG_NET_L2_WIFI_SHELL=y
CONFIG_NET_MGMT_EVENT_QUEUE_TIMEOUT=5000
CONFIG_NET_MGMT_EVENT_QUEUE_SIZE=16
CONFIG_NET_L2_WIFI_MGMT=y

CONFIG_NET_LOG=y
CONFIG_NET_L2_ETHERNET_LOG_LEVEL_DBG=n
CONFIG_NET_L2_WIFI_MGMT_LOG_LEVEL_DBG=y
CONFIG_NET_MGMT_EVENT_LOG_LEVEL_DBG=n
CONFIG_WIFI_LOG_LEVEL_DBG=y

# increase CONFIG_NET_BUF_DATA_SIZE to 512, allow more net buffer allocated.
CONFIG_NET_BUF_DATA_SIZE=512
# increase NET_MGMT_EVENT_STACK_SIZE to 1024, fix potential stack overflow issues.
CONFIG_NET_MGMT_EVENT_STACK_SIZE=1024
# increase SYSTEM_WORKQUEUE_STACK_SIZE to 2048, fix potential stack overflow issues.
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

# zperf
CONFIG_NET_ZPERF=y
# allow more ZVFS_POLL
CONFIG_ZVFS_POLL_MAX=16
#end of wifi


#for bmps
CONFIG_SHELL_BACKEND_SERIAL_RX_POLL_PERIOD=35
CONFIG_PM_NEED_ALL_DEVICES_IDLE=y
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_PM_DEVICE=y
CONFIG_PM_DEVICE_SYSTEM_MANAGED=y

#for debug
CONFIG_EXTRA_EXCEPTION_INFO=y
CONFIG_FAULT_DUMP=2
CONFIG_DEBUG_INFO=y
CONFIG_THREAD_NAME=y
CONFIG_PRINTK=y
CONFIG_ISR_STACK_SIZE=4096
CONFIG_THREAD_STACK_INFO=y
